### ISSUE TITLE
[Docs] flp.rst

### ISSUE THREAD

**Issue by fillipefeitosa** [joaopedroso/scipbook#1]
Thanks for sharing this document.

There is a lattex generating an error. Is Possible to correct it or provide a link for me to better understand what the method is suggesting.

```
\sum_{i=1}^n x_{ij} \leq M_j y_j & \mbox{ for } j=1,\cdots,m
```

Thanks.

**Comment by joaopedroso** [comment]
Thanks for pointing this out.
Hopefully, this is now corrected.
